name: SwiftPractice

options:
  deploymentTarget:
    iOS: 14.0
  developmentLanguage: ja
  useBaseInternationalization: false

packages:
  SnapKit:
    url: "https://github.com/SnapKit/SnapKit.git"
    version: 5.6.0

targets:
  SwiftPractice:
    type: application
    platform: iOS
    sources:
      - SwiftPractice
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: yossibank-yahoo.co.jp.swiftPractice
        CURRENT_PROJECT_VERSION: 1.0
        MARKETING_VERSION: 1.0
        DEVELOPMENT_LANGUAGE: jp
        PRODUCT_NAME: $(TARGET_NAME)
        INFOPLIST_FILE: SwiftPractice/Info.plist
      configs:
        debug:
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    dependencies:
      - package: SnapKit
    preBuildScripts:
      - script: |
          if which mint >/dev/null; then
            xcrun --sdk macosx mint run swiftformat .
          fi
        name: Run swiftformat
      - script: |
          if which mint >/dev/null; then
            git diff --name-only | grep .swift | while read filename; do
              xcrun --sdk macosx mint run swiftlint "$filename"
            done
          fi
        name: Run swiftlint

  SwiftPracticeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SwiftPracticeTests
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: SwiftPracticeTests/Info.plist
    dependencies:
      - target: SwiftPractice

  SwiftPracticeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - SwiftPracticeUITests
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: SwiftPracticeUITests/Info.plist
    dependencies:
      - target: SwiftPractice

schemes:
  SwiftPractice:
    build:
      targets:
        SwiftPractice: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - SwiftPractice
      targets:
        - name: SwiftPracticeTests
          parallelizable: true
          randomExecutionOrder: true
        - name: SwiftPracticeUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release